/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface Admgold24kPersonalCard {
        "firstName": string;
        "lastName": string;
        "photo": string;
        "resume": string;
        "role": string;
    }
    interface Admgold24kVideoPlayer {
        "provider": string;
        "source": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLAdmgold24kPersonalCardElement extends Components.Admgold24kPersonalCard, HTMLStencilElement {
    }
    var HTMLAdmgold24kPersonalCardElement: {
        prototype: HTMLAdmgold24kPersonalCardElement;
        new (): HTMLAdmgold24kPersonalCardElement;
    };
    interface HTMLAdmgold24kVideoPlayerElement extends Components.Admgold24kVideoPlayer, HTMLStencilElement {
    }
    var HTMLAdmgold24kVideoPlayerElement: {
        prototype: HTMLAdmgold24kVideoPlayerElement;
        new (): HTMLAdmgold24kVideoPlayerElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "admgold24k-personal-card": HTMLAdmgold24kPersonalCardElement;
        "admgold24k-video-player": HTMLAdmgold24kVideoPlayerElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface Admgold24kPersonalCard {
        "firstName"?: string;
        "lastName"?: string;
        "photo"?: string;
        "resume"?: string;
        "role"?: string;
    }
    interface Admgold24kVideoPlayer {
        "provider"?: string;
        "source"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "admgold24k-personal-card": Admgold24kPersonalCard;
        "admgold24k-video-player": Admgold24kVideoPlayer;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "admgold24k-personal-card": LocalJSX.Admgold24kPersonalCard & JSXBase.HTMLAttributes<HTMLAdmgold24kPersonalCardElement>;
            "admgold24k-video-player": LocalJSX.Admgold24kVideoPlayer & JSXBase.HTMLAttributes<HTMLAdmgold24kVideoPlayerElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
